language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt

script:
    - cd izp
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
    - pycodestyle . --exclude=polls/migrations
