language: python
python:
    - 3.6
install:
  - pip install -r requirements.txt    
  - pip install pep8
    
script:
  - python izp/manage.py makemigrations
  - python izp/manage.py migrate 
  - python izp/manage.py test
  - pep8 izp/manage.py.py