language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt    
    
script:
    - python izp/manage.py makemigrations
    - python izp/manage.py migrate 
    - python izp/manage.py test
    - pycodestyle . --exclude=izp/polls/migrations
